### ISSUE TITLE
Get current position of any mouse click on the map as lat/long and provide data restfull for the server

### ISSUE THREAD

**Issue by jh-RLI** [rl-institut/WAM_APP_FRED#10]
A user can click at any position on the map and the app returns the closest weather point and its property as feature on the map.

**Comment by Bachibouzouk** [comment]
I would split this in 2 issues which would be solved by two different PRs :  

1.  A user can click at any position on the map and a function returns the coordinates of the closest weather/powerplant point 

2.  A function fetches the properties of a weather point/power plant/timeseries based on the coordinates on that point

**Comment by jh-RLI** [comment]
- Frontend functionality
- data should be provided RESTFULL
- mouse-click position data needs to be in a usable format like lat/lng

**Comment by jh-RLI** [comment]
Good [example](https://gis.stackexchange.com/questions/210041/using-leaflet-js-is-it-possible-to-know-the-onclick-location-of-a-marker-ignor/210102) on how to get the mouse-click position using a Leaflet event handler that converts the (DOM)click event position to a lat/lng value
