### ISSUE TITLE
In feedin-tab missing plot in second selected region popup

### ISSUE THREAD

**Issue by jh-RLI** [rl-institut/WAM_APP_FRED#103]
Im not sure if this is already addressed somewhere. 

- If one clicks on th region to get the popup with feedin time series plot it works fine
- The second click on another region - without closing the popup from first selection - will show a popup without the plot

**Comment by jh-RLI** [comment]
@Bachibouzouk have you noticed this behavior?

**Comment by Bachibouzouk** [comment]
@jh-RLI - yet but only in the LOCAL_TESTING mode

**Comment by christian-rli** [comment]
@jh-RLI @Bachibouzouk I can confirm that this only happens in LOCAL_TESTING mode. Can this issue be closed then?
