### ISSUE TITLE
Provide description of the powerplant types

### ISSUE THREAD

**Issue by Bachibouzouk** [rl-institut/WAM_APP_FRED#119]
By using the `title` option of a the powerplant type `<div>` items, one can have hover information:

`<div title="information here"></div>`

**Comment by christian-rli** [comment]
I noticed that the numbers of my query and the queries powerplants don't add up. Namely my query shows fewer powerplants. I wanted to take a look at the query used to download the plants and noticed that the old table (in supply schema) is still used. So I'm going to update that. 

The issue with fewer plants probably has to with with generation_type and generation_subtypes used differently in both queries.  

**Update:** After closer inspection I can now say that both concerns were inaccurate. The new table is used and powerplants do add up.

**Comment by christian-rli** [comment]
addressed in #119 and merged in #121
