### ISSUE TITLE
There is no LICENSE.md file

### ISSUE THREAD

**Issue by Bachibouzouk** [rl-institut/WAM_APP_FRED#16]

**Comment by christian-rli** [comment]
We publish our tools under AGPL whenever possible. I added an AGPL license file. Can this issue be closed?

**Comment by Bachibouzouk** [comment]
@christian-rli - yes we can :). In the future it is better to close Issue with PR and not to push directly to dev ^^

**Comment by christian-rli** [comment]
> In the future it is better to close Issue with PR and not to push directly to dev ^^

Noted. Thx :)
