### ISSUE TITLE
Integrate style templates 

### ISSUE THREAD

**Issue by jh-RLI** [rl-institut/WAM_APP_FRED#2]
- See template progress: https://github.com/rl-institut/WAM/issues/11

**Comment by jh-RLI** [comment]
Integrated a first version Layout for the SinglePageApplikation. 
Development progress can be found in branch: **feature/WebGUI**

**Comment by christian-rli** [comment]
I'm going to work on feature/WebGUI (or rather a new branch thereof) to beautify the current state. One thing I noticed: Creating a fresh clone of WAM and WAM_APP_FRED, the app won't start. 

error:

TemplateSyntaxError at /WAM_APP_FRED/
'leaflet_tags' is not a registered tag library. Must be one of: ...

solution:

add 'leaflet' under INSTALLED_APPS in wam/settings.py

**Comment by jh-RLI** [comment]
great, knew about that but there is no good documentation for setup steps like this. 
Should be mentioned in an app specific "app_setup.txt" or something like that.

**Comment by christian-rli** [comment]
I think this can be considered done.
