### ISSUE TITLE
View fetches data about weather point depending on provided mouse-click(lat/lng)

### ISSUE THREAD

**Issue by jh-RLI** [rl-institut/WAM_APP_FRED#20]
- backend functionality 
- view should be created as class method within the Serializer class
- view returns data about the closest weather point to any provided mouseclick position
- position should be provided as lat/lng value
- fetched information should be provided at an URL 

See #10 for further information on how the mouse-click position is provided

**Comment by jh-RLI** [comment]
Good [example](https://stackoverflow.com/questions/24152420/pass-dynamic-javascript-variable-to-django-python) on how to transfer data from client to server using a RESTfull approach with HTTP POST.

**Comment by jh-RLI** [comment]
@Bachibouzouk this is already done in feature/weathe_data. You also did this in your scripts i believe? Are we still need this issue since you also already did futher dev. in local_tests?

**Comment by jh-RLI** [comment]
based on #10 the lat/lng is provieded for this view

**Comment by jh-RLI** [comment]
#29 query to fetch data

**Comment by Bachibouzouk** [comment]
@jh-RLI - I merged `local_tests` in `feature/weather_data`, I will mention this issue in the `feature/weather_data` PR, and we'll close it when the PR will be merged :)
