### ISSUE TITLE
Figure out how to build a query for the open fred data

### ISSUE THREAD

**Issue by Bachibouzouk** [rl-institut/WAM_APP_FRED#29]

**Comment by christian-rli** [comment]
There is no _real_ documentation for the oedialect (yet), but there are a few tutorials, mainly written by @Ludee [here](https://github.com/OpenEnergyPlatform/examples/tree/master/api). At the end of [api_tutorial_part_2](https://github.com/OpenEnergyPlatform/examples/blob/master/api/OEP_API_tutorial_part2.ipynb) there are some options that we can use to write a function to filter the closest data point to any lat and lon in the database, namely GREATER and LOWER. It may not be as comfortable or sleek as a PostGIS query, but I imagine it should work.

**Comment by christian-rli** [comment]
Maybe [this](https://github.com/OpenEnergyPlatform/examples/blob/master/api/OEP-oedialect_upload_from_csv.ipynb) helps as well. To quote from the Tutorial:

> Now we'll create an sql-alchemy-engine. The engine is what 'speaks' oedialect to the data base api. 

I have a fuzzy understanding of what exactly oedialect will accept and therefore how freely we can query overall, but this sounds to me like an [sql-alchemy-engine](https://docs.sqlalchemy.org/en/13/core/engines.html) will try to query anything via oedialect that we're able throw at it via sqlalchemy.

**Comment by jh-RLI** [comment]
Okay, to sum this up we use SQLAlchemy to Query the DB. There are just different ways how to create the engine? 

1. SQLAlchemy
```
from sqlalchemy import create_engine

DB_URL = '{ENGINE}://{USER}:{PASSWORD}@{HOST}:{PORT}/{NAME}'.format(**wam_config)
engine = create_engine(DB_URL)
```

2. SQLAlchemy + Dialect:
```
import sqlalchemy as sa
import oedialect

OEP_URL = 'openenergy-platform.org' #'193.175.187.164' #'oep.iks.cs.ovgu.de'
OED_STRING = f'postgresql+oedialect://{user}:{token}@{OEP_URL}'
engine = sa.create_engine(OED_STRING)
```

Then we can simply

```
sqlahelper.add_engine(engine, 'oep_engine')
```

**Comment by Bachibouzouk** [comment]
@Ludee explained me about the history of the configuration file handlers to access databasis, we can find inspiration in the [mastR](https://github.com/OpenEnergyPlatform/data-preprocessing/blob/master/data-import/bnetza_mastr/sessions.py) project. This comes a package to manage the psycopg2 requests: oemof.io (pg access). It was also used in ego.io (pg+oedb access) and reeem.io (pg+reeem_db access) before being used for the first time with SQLAlchemy in mastR (SOAP API).

@Ludee also mentionned this [website](http://postgrest.org/en/v5.2/) as a good reference.

**Comment by Bachibouzouk** [comment]
Done in be70112301110d12e14b6f8248718943eda8b858
