### ISSUE TITLE
Add custom geojson serializer 

### ISSUE THREAD

**Issue by jh-RLI** [rl-institut/WAM_APP_FRED#3]
- Integrate data from non django database
- provide data as geojson using https://pypi.org/project/geojson/

**Comment by jh-RLI** [comment]
Use This aproach to query a lot of data:
https://github.com/sqlalchemy/sqlalchemy/wiki/WindowedRangeQuery

**Comment by jh-RLI** [comment]
- serializer now working for Locations table and returns a GeoJson
- the GeoJson is provided at an URL by Django. It can be assigned to an JS variable and used in further dev.

**Comment by jh-RLI** [comment]
Serializer is developed here: https://github.com/rl-institut/WAM_APP_FRED/blob/feature/oep_serialize/serial_views.py

**Comment by Bachibouzouk** [comment]
@jh-RLI I think this issue can be closed now, no?

**Comment by Bachibouzouk** [comment]
Closed by #9
