### ISSUE TITLE
There is no layers of Germany's landkreis on the map

### ISSUE THREAD

**Issue by Bachibouzouk** [rl-institut/WAM_APP_FRED#36]

**Comment by jh-RLI** [comment]
There is the [vg250](http://www.geodatenzentrum.de/geodaten/gdz_rahmen.gdz_div?gdz_spr=deu&gdz_akt_zeile=5&gdz_anz_zeile=1&gdz_unt_zeile=15&gdz_user_id=0) data available at OEP.

**Comment by Bachibouzouk** [comment]
This was closed by #37
