### ISSUE TITLE
Add LeafletCluster to leafletmap

### ISSUE THREAD

**Issue by jh-RLI** [rl-institut/WAM_APP_FRED#48]
We want to visualize many datapoints on a map, therefore we need to cluster this data in order to keep the WEB-APP performance. 

I recomend to try this [plugin](https://github.com/Leaflet/Leaflet.markercluster) first since there is know-how in the team @christian-rli. 

This needs to be integrated in the "power plant register map"- we have many datapoints there. The data is already included on the map (test region: Berlin). 

The power plant register is currently developed in this branch: 
feature/powplreg

While running the WAM the data is porvided as geojson and can be found at this url: ..../WAM_APP_FRED/PowerPlantRegister.data/

**Comment by 4lm** [comment]
Nice plugin! Correct URL for link is: https://github.com/Leaflet/Leaflet.markercluster

**Comment by jh-RLI** [comment]
@christian-rli I think this could be essential to implement before next Tuesday. The amount of datapoints will have a heavy impact on the performance (one cant interact with the map anymore).  
ATM there would be just one other solution which is to limit the query, this should be avoided in my opinion. 

PS: Thanks for the correct link @4lm
