### ISSUE TITLE
FRED app rewrites leaflet config

### ISSUE THREAD

**Issue by nesnoj** [rl-institut/WAM_APP_FRED#49]
Hey folks,

@christian-rli has put the FRED app on the WAMdev yesterday.
Unfortunately, [your map coordinates](https://github.com/rl-institut/WAM_APP_FRED/blob/d06ddaf18196f8cfdabe46e97f33973814e4ec87/settings.py#L30) (where the map is positioned on startup) defined in param `DEFAULT_CENTER` of `LEAFLET_CONFIG` override [mine](https://github.com/rl-institut/WAM_APP_stemp_abw/blob/765e0b91c725f908e9121853e5188a4d9c559ca2/settings.py#L32) :( . (if I deactivate FRED, everything's fine)

This is a general WAM settings problem, see https://github.com/rl-institut/WAM/issues/74

Hence, it's the same with other leaflet params as well such as `TILES`, `SRID` etc.

There seems to be a [workaround](https://github.com/makinacorpus/django-leaflet/issues/59) for django-leaflet (different configs for multiple maps) but we need a general fix on WAM-level.

**Comment by jh-RLI** [comment]
oh great I always wondered why my zoom level and initial coords are not changing, now I know its because I have the ego_vis and fred wam installed.

**Comment by christian-rli** [comment]
I have put FredWAM on the production server as well, btw... and indeed the same problems seem to occur. I'm going to take it off a gain until there is a fix for this.

**Comment by nesnoj** [comment]
Yes, please!!

**Comment by nesnoj** [comment]
Urgently

**Comment by christian-rli** [comment]
Sorry, forgot to rerun the docker after changing the YAML-file. It's back to normal now.

**Comment by nesnoj** [comment]
Ok, implemented a solution for this specific *django-leaflet*-related issue in https://github.com/rl-institut/WAM_APP_stemp_abw/pull/66 using a simple settings override.

You might wanna do the same..
