### ISSUE TITLE
Create draft of the tool and delineate functionality

### ISSUE THREAD

**Issue by christian-rli** [rl-institut/WAM_APP_FRED#5]
Make a drawing or create an image of the planned tool and briefly describe its functions.

**Comment by christian-rli** [comment]
First draft on a whiteboard:
![Draft_WAM_APP_FRED](https://user-images.githubusercontent.com/42000429/57073045-20c89080-6ce0-11e9-9628-12ef6b389c12.jpg)

**Comment by christian-rli** [comment]
Mockup Created by @jh-RLI :
![Mockup_WAM_FRED_SinglePage_v2](https://user-images.githubusercontent.com/42000429/57073100-54a3b600-6ce0-11e9-831f-0598481413dc.png)

**Comment by christian-rli** [comment]
TODO: Write a description on how this app is meant to work.

**Comment by christian-rli** [comment]
To sum up our priorities for the time being (from meeting in May):
- show weather data (simple, with preselected variables: windspeed at 10m and 140m, Variable selection is a nice-to-have). idea: click on map and receive weather data of closest point(s)
- show power plants (not everything is visible at top level, after selection of area, power plants become visible, ability to click and download are nice to haves)
- resolution for time series: Landkreise

Our goal is to visualize all three of the above. If we can win some time by cutting some functionality or time consuming visualization, we should do that.

Priority: Finishing our project
We should be able to show something in mid June
Quality criteria: 1. works 2. works quickly

Appointments scheduled in May:
12 June data embedded EK, CH, PF, JH
29 May EK, PF, JH, SH

**Comment by jh-RLI** [comment]
**3-Schichten-Modell WAM_APP_FRED**
![3-Schichten-Modell WAM_APP_FRED](https://user-images.githubusercontent.com/38939526/59361035-8709ef80-8d31-11e9-96a3-bc5d8bf22b70.jpg)
 @Bachibouzouk @christian-rli this could be helpful for us if we talk about what we work on. Feel free to give me feedback on this.
