### ISSUE TITLE
urgent tasks

### ISSUE THREAD

**Issue by jh-RLI** [rl-institut/WAM_APP_FRED#59]
What should be done (pls add missing):
- [x] Include input from html from in weather data click query ( done in 14cf1e8dc24f130e30f068b5b6d4863eccbf1db5)
- [x] Implement highcart functionality for TimeSeries
- [x] Split the functionality of WeatherData and PowerPlant so they deactivate/activate depending on the selectet sidemenue-tab(Weather Data, Power Plant Register, Feedin-Time Series)
- [x] Fix mouseover-highlighting

**Comment by Bachibouzouk** [comment]
I can take care of the second one

**Comment by jh-RLI** [comment]
@Bachibouzouk @christian-rli is this done? do you whant to update?

**Comment by Bachibouzouk** [comment]
@jh-RLI, everything here is done --> closing the issue
