### ISSUE TITLE
CSV export feature

### ISSUE THREAD

**Issue by jh-RLI** [rl-institut/WAM_APP_FRED#60]
Provide export functionality for currently displayed data.

**Comment by christian-rli** [comment]
@Bachibouzouk how long would implementing a simple button or link in the popup window for weather take?

**Comment by Bachibouzouk** [comment]
@christian-rli - not long, what took some time was the chained dropdowns for the variable ^^, I merge #107 and #109 first and then I add the button :)

**Comment by Bachibouzouk** [comment]
Done in #112
