### ISSUE TITLE
Requirement.txt is not up-to-date

### ISSUE THREAD

**Issue by Bachibouzouk** [rl-institut/WAM_APP_FRED#8]
Missing packages
- sqlahelper

- geoalchemy2

- shapely

- geojson

**Comment by jh-RLI** [comment]
Thats true, most of the work that is up to date can be found in branch: feature/oep_serialize. There is a more complete wam_environment.yml file with all the packages needed. Maybe you can give me feedback if this file will work/is complete. There might be redundant packages that are already included in the base wam environment. 

Maybe its time to merge at least some changes in dev :)
