### ISSUE TITLE
Missing Regions in Feedin-Tab

### ISSUE THREAD

**Issue by christian-rli** [rl-institut/WAM_APP_FRED#93]
In the Feedin-Tab on the map it doesn't matter where one clicks, the same result is always returned. Regional selection should be implemented, even with data missing thus far.

**Comment by Bachibouzouk** [comment]
Yes, for that we need the dictionnary with nuts and region name (and geometry, if oedialect finally manages the selection with geometry :))

**Comment by christian-rli** [comment]
NUT codes for the calculated feedin is taken from [this table](https://openenergy-platform.org/dataedit/view/boundaries/bkg_vg250_4_krs) . I created a simplified geojson (~10MB) from it.

Here's the attribute table: [nuts3_germany.xlsx](https://github.com/rl-institut/WAM_APP_FRED/files/3396318/nuts3_germany.xlsx)

I can turn it into a dictionary, too.

**Comment by christian-rli** [comment]
python-dictionary:
[nuts3_germany_dictionary.txt](https://github.com/rl-institut/WAM_APP_FRED/files/3396443/nuts3_germany_dictionary.txt)

**Comment by christian-rli** [comment]
I looked at the attribute table a bit closer again. Some lines were duplicates (my guess is, because they originate from a multipolygon). I removed all the duplicate entries in the dictionary. 

FYI some of the values appear several times (like e.g. Heilbronn, Karlsruhe and Rostock), but the dict now only has unique keys.  

[nuts3_germany_dictionary.txt](https://github.com/rl-institut/WAM_APP_FRED/files/3396543/nuts3_germany_dictionary.txt)

**Comment by christian-rli** [comment]
TODO: Create list of subregions (nuts-region) contained in regions.
list formatted like "DE-...":[   ]

**Comment by christian-rli** [comment]
I looked into NUTS. Larger regions are conveniently contained in the string for a subregion. [Wikipedia](https://de.wikipedia.org/wiki/NUTS:DE) helps. A region code like **DE4**0I (Uckermark) will be contained by **DE4** (Brandenburg). So to find out the upper region / Bundesland in Germany, we can just take the first three alphanumericals of any given code. I looked at our data set and it checks out.  

Nonetheless I created a geojson with an extra columns for Bundesländer and NUTS 1 codes. I'm going to use it to create a simplified germany map as well, hopefully of a similar size as the one we're currently using. It's nasty business when the layers don't overlap :)

**Comment by Bachibouzouk** [comment]
```
import geopandas as gpd

gb = gpd.read_file('static/WAM_APP_FRED/geodata/germany.geojson')

glk = gpd.read_file('static/WAM_APP_FRED/geodata/Germany_NUTS3_simplified.geojson')

landkreis_map_to_region = {}
for i, name in enumerate(gb.name):
    lk_in_region = glk.loc[glk.geometry.map(lambda x: x.centroid.within(gb.iloc[i, -1]))]
    landkreis_map_to_region[name] = lk_in_region.nuts.to_list()
```

**Comment by jh-RLI** [comment]
Im using the germany_nuts_3.geojson from your temp filder @christian-rli. This functions returns
the nuts_1 code based on the region name. 

```
    def nuts_1_for_region(self, ppr_region):

        nuts_1 = []
        # load the map ot the landkreis for each region
        with open(
                # 'WAM_APP_FRED/static/WAM_APP_FRED/geodata/landkreis_map_to_region.json',
                'WAM_APP_FRED/static/WAM_APP_FRED/geodata/germany_nuts_3.geojson',
                encoding='UTF-8'
        ) as g:
            gj_to_lk = json.load(g)

            for i, f in enumerate(gj_to_lk['features']):
                if ppr_region in f['properties']['region']:
                    nuts_1_temp = f['properties']['nuts_1']
                    if nuts_1_temp not in nuts_1:
                        nuts_1.append(nuts_1_temp)

        return nuts_1
```
