### ISSUE TITLE
Missing credits for map tiles

### ISSUE THREAD

**Issue by christian-rli** [rl-institut/WAM_APP_FRED#95]
I noticed that we have a (nice looking) mapbox-streets layer without proper attribution. This is [required](https://docs.mapbox.com/help/how-mapbox-works/attribution/). So we just need to link to mapbox in the credits at the bottom of the map. 

@jh-RLI out of interest: where did we get the token and is it registered to anyone?

**Comment by jh-RLI** [comment]
@christian-rli I implemented this without knowing about access token :) so I think this could be related to Jonathan.

**Comment by nesnoj** [comment]
Uh, wasn't aware of this, thank you.
Changed in StEmp ABW in https://github.com/rl-institut/WAM_APP_stemp_abw/commit/8872cc34d3066473653a73f5ed6938ee045d56eb
Is there a reason why you omitted the [required](https://docs.mapbox.com/help/how-mapbox-works/attribution/#text-attribution) "Improve this map"?

I think the token was copied from a leaflet example, it's not ours.. o_O

**Comment by christian-rli** [comment]
> Is there a reason why you omitted the [required](https://docs.mapbox.com/help/how-mapbox-works/attribution/#text-attribution) "Improve this map"?

Whoops. No reason. I guess I didn't read it all.

> I think the token was copied from a leaflet example, it's not ours.. o_O

Hm. I recall that tiles are free and all - up to a point where mapbox will approach you (no source for this info, just vague remnants of an old memory). Maybe we should just get our own token with one of our rli-addresses? I hope there aren't any limitations for non-human entities.

**Comment by Bachibouzouk** [comment]
Closed in #108
