### ISSUE TITLE
Powerplants not filtered by scenario  and version?

### ISSUE THREAD

**Issue by christian-rli** [rl-institut/WAM_APP_FRED#96]
I took a closer look at [ego_dp_res_powerplant](https://openenergy-platform.org/dataedit/view/supply/ego_dp_res_powerplant) (btw, if you download it, it's 16GB). I queried it for powerplants without a nuts code, which resultet in ~5 million powerplants. 

@Ludee informed me that the table contains a bunch of duplicates, for different scenarios and versions. 

@jh-RLI do we filter for these within the app?

**Comment by christian-rli** [comment]
In scenario "Status Quo" there are about 5% of windpower plants without a nuts code (all of them off-shore) + a couple dozen solar power plants out of several million. I think we can neglect those for now.

**Comment by jh-RLI** [comment]
@christian-rli yes we do filter them otherwise the query would take to long. 

We use a config file to manage requirements like this. 

I also had a closer look at the query and noticed that I was missing one of the values in the query filter.
I will fix this now and create a PR.

Example fyi :)

EGO_DP_SCENARIO is filtered 
EGO_DP_VERSION is missing :/ 
```
tbl_cols = Bundle(
                    'powerplant',
                    res_powerplant_tbl.id,
                    res_powerplant_tbl.version,
                    res_powerplant_tbl.generation_type,
                    res_powerplant_tbl.generation_subtype,
                    res_powerplant_tbl.scenario
                )

oep_query = Serializer.session.query(
                    res_powerplant_tbl.rea_geom_new.ST_Transform(4326),
                    tbl_cols
                ) \
                    .filter(
                        and_(
                            # tbl_cols.c.rea_geom_new.ST_Transform(4326).ST_Within(wkb),
                            res_powerplant_tbl.rea_geom_new.ST_Transform(4326).ST_Within(wkb),
                            tbl_cols.c.scenario == EGO_DP_SCENARIO,
                            tbl_cols.c.generation_type == generation_type
                        )
                    )
```

**Comment by jh-RLI** [comment]
The query is clearly not the problem anymore. The response is quit fast. But if we want to render all datapoints on the map this will still be a problem (even with marker cluster). Some regions containing to many datapoints which will lead the website to crash. 
If one zooms to a certain zoom level this will happen with pretty much all regions. I think this will be the most difficult problem to slove. 
The only easy solution would be to use smaler regions. @christian-rli

**Comment by jh-RLI** [comment]
Another solution I can think of would be to "query" the Geojson with javascript and just render what is in the current display size (what the user can see at this moment). I think there might even be leaflet functionality to do that.  @christian-rli 

I will create a new issue :)
