### ISSUE TITLE
Optimize data rendering in Power Plant Register 

### ISSUE THREAD

**Issue by jh-RLI** [rl-institut/WAM_APP_FRED#98]
- Some regions containing to many datapoints which will lead the website to crash.
- If one zooms to a certain zoom level the performance will decrease.

**Comment by jh-RLI** [comment]
Handel Zoom and drag events on map with following lefalet js events:
moveend: fired when center of map stoped changing
zoomend: fired when after zoom animation finished

Just show elements in current geographical bounds with leaflet js function:
getBounds(): returns LatLngBounds for currently visible map 

fitBounds(): Create map view for geographical bounds with max zoom level


Further Information : https://leafletjs.com/reference-1.4.0.html

**Comment by jh-RLI** [comment]
Leaflets geojson got a filter functionality.
The features in a geojson can be filteres before they are rendered.

See: https://leafletjs.com/reference-1.5.0.html#geojson-filter

**Comment by Bachibouzouk** [comment]
Isn't it what the clusters are doing?

**Comment by jh-RLI** [comment]
For part of the problem it might be a possibility to adjust the cluster so the markers stay in a cluster even on lower zoom levels. But there is still the problem that for some regions (Like "Nidersachsen" in "photovoltaik") the website will crash even with clustered markers. I havent worked with the clustermarker myself @christian-rli implemented this.

**Comment by Bachibouzouk** [comment]
We could also make use of one of those functions

```
map.on('zoomend', function(event) {
    console.log(map.getZoom())
    console.log('end zooming')
    console.log(map.getBounds())
    console.log(map.getCenter())
});
```

**Comment by christian-rli** [comment]
#105 took care of this issue.
